version: 2
updates:
  # Enable version updates for .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "pandapknaepel"
    assignees:
      - "pandapknaepel"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "pandapknaepel"
    assignees:
      - "pandapknaepel"
    commit-message:
      prefix: "chore"
      include: "scope"